server:
  port: 18010
spring:
  application:
    name: microservice-consumer-movie
  cloud:
    consul:
      host: 10.19.141.152
      port: 8068
logging:
  level:
    com.itmuch.cloud.study.user.feign.GateDetectionFeignClient: DEBUG